docs/documentation/maya/1.0.0/ribbon.md
@carlosmonteagudoinbibo 
Our engine does not parse this table style; the final look is obtained using the website stylesheets. So this can be avoided
=> [Fix] Remove table syles

docs/documentation/maya/tools.md
Tools documented.
tools.md
Issue of this PR: https://github.com/Inbibo/adonisfx_docs/issues/19
=> #19 Maya v1.0.0 Tools docs

docs/documentation/maya/simshape.md
@carlosmonteagudoinbibo this PR fix list issues in Simshape page
Basically this is dued to the presence of newlines between lists elements
Let me know if anything is unclear
=> fix list spaces

docs/documentation/maya/edge_evaluator.md
Hello, I have suggested possible changes to the titles, bearing in mind that on an HTML page, there can only be one H1 title (the main title). We have developed a contextual page menu which, in order to divide the content and allow you easy navigation, retrieves all the h2 and h3  (h4 excluded) on the page and arranges them in a menu.
keep this in mind organizing the contents
Thank you
=> Title change proposal

docs/licensing.md
This pull request fix the Licensing file view
=> Fix licensing file

docs/licensing.md
- Installation of server is not mandatory.
- We remove it for now until we confirm it is usable
=> Remove installation flags (-i) example from the documentation

docs/installation.md
- Fix reference link to images in installation.md
=> #50 Fix reference to /images in installation.md page

docs/release_notes.md
Documentation completed and released here: https://inbibo.co.uk/docs/adonisfx/v1.0.1/introduction
=> Completed documentation of AdonisFX v1.0.1 for Maya

docs/licensing.md, docs/release_notes.md
Documentation completed and published here: https://inbibo.co.uk/docs/adonisfx/v1.0.2/introduction
=> Completed documentation of AdonisFX v1.0.2 for Maya

docs/release_notes.md
- Adds bug fixes section in Release Notes for v1.0.4
=> #67 Update release notes for version v1.0.4

docs/release_notes.md
- Fixed the issue number of a known limitation.
=> Release v1.1.0 fix issue number

docs/maya/muscle.md, docs/maya/ribbon.md, docs/maya/simshape.md, docs/maya/skin.md, docs/release_notes.md
- This PR adds the documentation for v1.1.1
- The changes added are:
- Description of the bugfix in release notes
- Clarification in the description of the gravity attribute in all pages
=> #85 Adds release notes for v1.1.1

docs/terminology.md
- Adds definition for Volume Shape Preservation in Constraint section
- Adss definition for Fat solver
=> #101 Update terminology with content for v1.3.0

docs/faq.md, docs/licensing.md, docs/release_notes.md
- Improved the floating licensing setup to allow connection with both interactive and batch servers without the need of a switch in the environment configuration. This change is fully backward compatible. AdonisFX-1384
=> Release v1.3.1 onto main

docs/maya/muscle.md, docs/maya/ribbon.md, docs/maya/simple_setup.md
- Updated notes mentioning the muscle-to-muscle limitation for attach to geo and slide on geo constraints.
=> #129 Muscle to muscle attachments 1.4.0

docs/release_notes.md
- Updated release notes for version 1.4.1.
=> #154 Update docs for 1.4.1

docs/release_notes.md
=> #159 Release Notes 1.5.0

docs/maya/deformers/muscle.md, docs/maya/deformers/ribbon.md, docs/maya/tools.md
Tasks done:
- Added note to AdnMuscle and AdnRibbonMuscle page informing about the paintable status of Fibers and Tendons
- Added note to the tools section with a similar message
=> #175 Fibers Tendons Init Painting 1.5.0

docs/maya/api.md
Updating api.md to align with the final integraion of the experimental API
Note: CAUTION does not render properly in the Preview Tool anymore. We keep NOTE for now until we have time to understand what the problem is.
=> #182 Updates in api.md

docs/release_notes.md
- Update release date of v1.6.0, as it was planned for 18th of March and we are finally releasing on the 21st.
=> Update release date of v1.6.0

docs/release_notes.md
This pull request includes an update to the `docs/release_notes.md` file to add the release notes for version 1.6.1. The update includes a bug fix for a memory reallocation issue in certain utility methods during initialization.
* [`docs/release_notes.md`](diffhunk://#diff-3fa44f20fe1c12758e313ededbc4847b3434a9fa307dbcc493bcade14995dd5fR3-R8): Added release notes for version 1.6.1, including a bug fix for memory reallocation issue on initialization of certain utility methods.
=> #216 Added docstrings about memory allocation issue

docs/release_notes.md
Update release date of 1.7.0: 2025-05-28
=> Update release date of 1.7.0

docs/release_notes.md
[GO](https://inbibo.co.uk/docs/preview?sheet_url=https%3A%2F%2Fgithub.com%2FInbibo%2Fadonisfx_docs%2Fblob%2Fae7a89ee0fce5662942814531ea7a11fbecb1f7c%2Fdocs%2Frelease_notes.md)
This pull request updates the release notes to include details about version 1.7.1. The update documents a bug fix related to the logger functionality in batch mode.
Release notes update:
* [`docs/release_notes.md`](diffhunk://#diff-3fa44f20fe1c12758e313ededbc4847b3434a9fa307dbcc493bcade14995dd5fR3-R9): Added an entry for version 1.7.1, including the fix for a bug that prevented the logger from displaying messages in batch mode.
=> #246 Updated Release Notes for v1.7.1

docs/release_notes.md
This pull request updates the release notes in `docs/release_notes.md` for version 1.7.2, highlighting improvements to the floating licensing system and paint tool, as well as a bug fix for the muscle solver.
* **Improvements**:
- Enhanced the floating licensing system to immediately release leases upon Maya exit.
- Updated the Paint Tool to support multiple materials on the same paintable geometry.
* **Bug Fixes**:
- Resolved an issue where the muscle solver failed to initialize if input geometry contained disconnected primitives. (*AdonisFX-2111*)
=> Release v1.7.2 for Maya
